apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-pvc
spec:
  accessModes:
    - {{ .Values.persistence.notifications.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.notifications.size }}
  storageClassName: {{ .Values.persistence.notifications.storageClass }}

