apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites-pvc
spec:
  accessModes:
    - {{ .Values.persistence.sites.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.sites.size }}
  storageClassName: {{ .Values.persistence.sites.storageClass }}

