apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gdesk.name" . }}-glpi-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gdesk.name" . }}-glpi-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gdesk.name" . }}-glpi-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
