apiVersion: v1
kind: Service
metadata:
  name:  {{ template "gdesk.fullname" $ }}-glpi
spec:
  selector:
    app:  {{ template "gdesk.name" . }}
  type: {{ .Values.service.type }}
  ports:
  - name:  http
    port:  {{ .Values.service.port }}
    targetPort:  80
