apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gdesk.fullname" . }}-glpi
  labels:
    app: {{ template "gdesk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "gdesk.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "gdesk.name" . }}
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: volume-permissions
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', 'chown -R 33:33 /var/www/html']
        volumeMounts:
        - name: {{ template "gdesk.name" . }}-glpi-config
          mountPath: /var/www/html/glpi/config
        - name: {{ template "gdesk.name" . }}-glpi-files
          mountPath: /var/www/html/glpi/files
        - name: {{ template "gdesk.name" . }}-glpi-plugins
          mountPath: /var/www/html/glpi/plugins
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name:  {{ template "gdesk.name" . }}-glpi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: {{ template "gdesk.name" . }}-glpi-config
            mountPath: /var/www/html/glpi/config
          - name: {{ template "gdesk.name" . }}-glpi-files
            mountPath: /var/www/html/glpi/files
          - name: {{ template "gdesk.name" . }}-glpi-plugins
            mountPath: /var/www/html/glpi/plugins
      volumes:
      - name: {{ template "gdesk.name" . }}-glpi-config
        persistentVolumeClaim:
          claimName: {{ template "gdesk.name" . }}-glpi-config
      - name: {{ template "gdesk.name" . }}-glpi-files
        persistentVolumeClaim:
          claimName: {{ template "gdesk.name" . }}-glpi-files
      - name: {{ template "gdesk.name" . }}-glpi-plugins
        persistentVolumeClaim:
          claimName: {{ template "gdesk.name" . }}-glpi-plugins


