apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gdesk.name" . }}-mariadb
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mariadb-glpi-user: {{ randAlphaNum 8 | b64enc | quote }}
  mariadb-glpi-password: {{ randAlphaNum 16 | b64enc | quote }}
