apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gdesk.name" . }}-mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi