apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gdesk.name" . }}-mariadb
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mariadb-glpi-user: {{ randAlphaNum 8 | b64enc | quote }}
  mariadb-glpi-password: {{ randAlphaNum 16 | b64enc | quote }}
