apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gdesk.name" . }}-mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}