apiVersion: v1
kind: Service
metadata:
  name: {{ template "gdesk.name" . }}-mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: {{ template "gdesk.name" . }}-mariadb
  clusterIP: None